language: node_js
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - nvm install 7.5.0
  - npm install -g npm@4 typescript@2.2.1 codecov && node -v && npm -v

install:
  - npm install

script:
  - tsc && npm test

after_success:
  - codecov
